### ISSUE TITLE
Add gosec in the default pipeline for Golang projects

### ISSUE THREAD

**Issue by vitsalis** [babylonlabs-io/.github#9]
Deliverables:
- [x] `gosec` is added to the reusable build pipeline
- [ ] Test and bump version on every service
- [ ] Return findings to service owners for resolution

**Comment by filippos47** [comment]
The pipeline is now supported.
Adoption and issue resolution to be handled by the corresponding service owners based on this process: https://babylonlabsworkspace.slack.com/archives/G07ES6D66AD/p1727051854733549
